# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- deploy

build-job:
  stage: deploy
  script:
    - echo 'START'
    - cd ~/webservices/prod-finplan/finplan-base-web
    - git pull
    - yarn
    - NODE_OPTIONS=--max-old-space-size=2048 NODE_ENV=production quasar build
    - if [ -d "dist/spa-production/" ]; then rm -rf dist/spa-production; fi
    - cp -r dist/spa dist/spa-production
    - if [ -d "../finplan-ssr/public/spa" ]; then rm -rf ../finplan-ssr/public/spa; fi
    - cp -r dist/spa-production ../finplan-ssr/public/spa
    - pm2 restart finplan-web
    - echo 'FINISH BUILD'
